"""Add reviewer form assignments

Revision ID: 4459c4d00b23
Revises: 76310d865a38
Create Date: 2026-09-01 19:32:47.881774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4459c4d00b23'
down_revision = '76310d865a38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reviewer_form_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('xlsform_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('first_opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_saved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['xlsform_id'], ['xlsforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'xlsform_id', 'language_id', name='uq_reviewer_form_assignment')
    )
    with op.batch_alter_table('reviewer_form_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reviewer_form_assignments_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviewer_form_assignments_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reviewer_form_assignments_xlsform_id'), ['xlsform_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reviewer_form_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reviewer_form_assignments_xlsform_id'))
        batch_op.drop_index(batch_op.f('ix_reviewer_form_assignments_user_id'))
        batch_op.drop_index(batch_op.f('ix_reviewer_form_assignments_language_id'))

    op.drop_table('reviewer_form_assignments')
    # ### end Alembic commands ###
