"""Add questionnaire review models

Revision ID: 76310d865a38
Revises: ed0d0a93f96b
Create Date: 2026-09-01 18:59:04.580369

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76310d865a38'
down_revision = 'ed0d0a93f96b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('choice_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xlsform_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('list_name', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('english_label', sa.Text(), nullable=True),
    sa.Column('raw_row_data', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['xlsform_id'], ['xlsforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xlsform_id', 'row_number', name='uq_choice_item_xlsform_row')
    )
    with op.batch_alter_table('choice_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_choice_items_list_name'), ['list_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_choice_items_xlsform_id'), ['xlsform_id'], unique=False)

    op.create_table('survey_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xlsform_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=40), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('list_name', sa.String(length=255), nullable=True),
    sa.Column('english_label', sa.Text(), nullable=True),
    sa.Column('raw_row_data', sa.JSON(), nullable=True),
    sa.Column('relevant', sa.Text(), nullable=True),
    sa.Column('appearance', sa.String(length=255), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['xlsform_id'], ['xlsforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xlsform_id', 'row_number', name='uq_survey_item_xlsform_row')
    )
    with op.batch_alter_table('survey_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_survey_items_list_name'), ['list_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_survey_items_xlsform_id'), ['xlsform_id'], unique=False)

    op.create_table('translation_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('xlsform_id', sa.Integer(), nullable=False),
    sa.Column('sheet_name', sa.String(length=40), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('original_cell_value', sa.Text(), nullable=True),
    sa.Column('extracted_translation', sa.Text(), nullable=True),
    sa.Column('edited_translation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('edited_by', sa.Integer(), nullable=True),
    sa.Column('edited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['edited_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ),
    sa.ForeignKeyConstraint(['xlsform_id'], ['xlsforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('xlsform_id', 'sheet_name', 'row_number', 'language_id', name='uq_translation_review_row_language')
    )
    with op.batch_alter_table('translation_reviews', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_translation_reviews_language_id'), ['language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_translation_reviews_xlsform_id'), ['xlsform_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('translation_reviews', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_translation_reviews_xlsform_id'))
        batch_op.drop_index(batch_op.f('ix_translation_reviews_language_id'))

    op.drop_table('translation_reviews')
    with op.batch_alter_table('survey_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_survey_items_xlsform_id'))
        batch_op.drop_index(batch_op.f('ix_survey_items_list_name'))

    op.drop_table('survey_items')
    with op.batch_alter_table('choice_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_choice_items_xlsform_id'))
        batch_op.drop_index(batch_op.f('ix_choice_items_list_name'))

    op.drop_table('choice_items')
    # ### end Alembic commands ###
