"""Add XLSForm import

Revision ID: ed0d0a93f96b
Revises: bd1387a8dab3
Create Date: 2026-09-01 18:45:48.406534

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed0d0a93f96b'
down_revision = 'bd1387a8dab3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xlsforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('form_title', sa.String(length=255), nullable=True),
    sa.Column('form_id', sa.String(length=255), nullable=True),
    sa.Column('version', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('survey_row_count', sa.Integer(), nullable=False),
    sa.Column('choices_row_count', sa.Integer(), nullable=False),
    sa.Column('detected_language_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_filename')
    )
    with op.batch_alter_table('xlsforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_xlsforms_uploaded_by'), ['uploaded_by'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('xlsforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_xlsforms_uploaded_by'))

    op.drop_table('xlsforms')
    # ### end Alembic commands ###
